In [8]:
#pandas practice
import pandas as pd 

#series from list or array..
sr=pd.Series([1,2,3,4,5,6,7,8])
print(sr[1:3])

sr=pd.Series([1,2,3,4,5,6,7,8],index=['h','b','c','d','e','f','g','a'])
print(sr)

pd.Series(5, index=[100, 200, 300])
print(sr)

1    2
2    3
dtype: int64
h    1
b    2
c    3
d    4
e    5
f    6
g    7
a    8
dtype: int64
h    1
b    2
c    3
d    4
e    5
f    6
g    7
a    8
dtype: int64


In [14]:
import pandas as pd 
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}

sr=pd.Series(population)
print(sr['California':'Illinois'])
print(sr.index)

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64
Index([u'California', u'Florida', u'Illinois', u'New York', u'Texas'], dtype='object')


In [20]:
import pandas as pd 

population=[38332521, 26448193,19651127,19552860,12882135]
#dataframe from list 
df=pd.DataFrame(population,columns=['Population'],index=['California', 'Florida', 'Illinois','New York','Texas'])
print(df)

#dataframe from dictionry.
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
df1=pd.DataFrame({'Population':population,'area':area})
df1

            Population
California    38332521
Florida       26448193
Illinois      19651127
New York      19552860
Texas         12882135


Population    area
California    38332521  423967
Florida       19552860  170312
Illinois      12882135  149995
New York      19651127  141297
Texas         26448193  695662

In [15]:
#dataframe form two dimentiona; Numpy Array..
import numpy as np
import pandas as pd

ar=np.random.randint(low=1,high=10,size=8).reshape(4,2)
NPdf=pd.DataFrame(ar,columns=['a','b'],index=np.arange(4))
NPdf

#Note  
print(NPdf.index[2])  #index value at 2 index
NPdf.index[2]=5     #try to change index ----Opppps Immutable index-can not be change--index are as Set in dataframe
                    #set can not be duplicate and change..

2


TypeError: Index does not support mutable operations

In [37]:
#data selection in series 
import numpy as np
import pandas as pd

ser=pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])
ser[(ser>3)&(ser<6)] #all other slicing operetaions are avaialbale..ser[1:3]..etc and loc[],iloc[] asl available.

#Data selection in DF
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
df1=pd.DataFrame({'Population':population,'area':area})
df1['Density']=df1.area/df1.Population
df1.loc[((df1.area<600000)&(df1.area>150000)),['Population','Density']] #print only few with limited columns.

Population  Density
California    38332521  0.01106
Florida       19552860  0.00871

In [5]:
#UFuncs
import numpy as np
import pandas as pd

population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
popu=pd.Series(population)
area=pd.Series(area)
density=popu/area
density
popu+area  #to check all other refer previour numpy notebook.


California    38756488
Florida       19723172
Illinois      13032130
New York      19792424
Texas         27143855
dtype: int64

In [16]:
#very new to learn
import numpy as np
import pandas as pd
a=np.random.randint(0,10,(3,4))
print(a-a[1])

df = pd.DataFrame(a, columns=list('QRST'))
print(df-df.iloc[0])
print(df.subtract(df['R'],axis=0))
alter=df.iloc[0,::2]
b=df-alter
b

[[-4  6 -3  6]
 [ 0  0  0  0]
 [-4  1 -3  3]]
   Q  R  S  T
0  0  0  0  0
1  4 -6  3 -6
2  0 -5  0 -3
   Q  R  S  T
0 -4  0 -6  1
1  6  0  3  1
2  1  0 -1  3


Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN  3.0 NaN
2  0.0 NaN  0.0 NaN

In [20]:
np.mean(b,axis=1)

0    0.0
1    3.5
2    0.0
dtype: float64

In [21]:
#functions 
#isnull()
#notnull()
#fillna()
#dropna()
df = pd.DataFrame([[1,np.nan, 2],[2,3,5],[np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [41]:
print(df[df.isnull()])
print(df[df.notnull()])
print(df.dropna(axis='rows'))
print(df.dropna(axis='columns'))

#set count how many can be nan
print(df.dropna(axis='columns',how='all'))
print(df.dropna(axis='columns',thresh=2))

    0   1   2
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
1  2.0  3.0  5
   2
0  2
1  5
2  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6


0      1  2
0    1.0 -999.0  2
1    2.0    3.0  5
2 -999.0    4.0  6

In [44]:
#filling na values
df.fillna(-999)
df.fillna(method='ffill')
df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

AttributeError: 'module' object has no attribute 'rand'

In [5]:
#concate and append
#pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
#keys=None, levels=None, names=None, verify_integrity=False,copy=True)

#for series
import numpy as np
import pandas as pd

sr1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
sr2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

print(pd.concat([sr1,sr2])) #diffrent indexs

sr1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
sr2 = pd.Series(['D', 'E', 'F'], index=[4, 3, 6])
print(pd.concat([sr1,sr2]))  #same index two times

try:
  print(pd.concat([sr1, sr2], verify_integrity=True)) #this will throw error if any index common 
except ValueError as e:
  print("ValueError:", e)

print(pd.concat([sr1, sr2], ignore_index=True))  #this will throw  not error if even any index common.
                                                 #it will give new index to


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object
1    A
2    B
3    C
4    D
3    E
6    F
dtype: object
('ValueError:', ValueError("Indexes have overlapping values: Int64Index([3], dtype='int64')",))
0    A
1    B
2    C
3    D
4    E
5    F
dtype: object


In [29]:
#for Data farame
df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'),index=[0, 1])
df4 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'), index=[0, 1])
print(df3)
print(df4)
print(pd.concat([df3,df4]))

try:
  print(pd.concat([df3, df4], verify_integrity=True)) #this will throw error if any index common 
except ValueError as e:
  print("ValueError:", e)

print(pd.concat([df3, df4], ignore_index=True)) #this will throw  not error if even any index common.
                                                 #it will give new index to

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1
('ValueError:', ValueError("Indexes have overlapping values: Int64Index([0, 1], dtype='int64')",))
    A   B
0  A0  B0
1  A1  B1
2  A0  B0
3  A1  B1


In [38]:
df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'),index=[0, 1])
df4 = pd.DataFrame([['C0','D0'],['C1','D1']], columns=list('CD'), index=[0, 1])
print(df3)
print(df4)
pd.concat([df3,df4],axis=1)

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [42]:
#join with concate
df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'),index=[0, 1])
df4 = pd.DataFrame([['C0','D0'],['C1','D1']], columns=list('CD'), index=[0, 1])
print(pd.concat([df3,df4],join='inner')) #by default join is union of input columns but 
                                         #if join='inner' it becomes intersection for input column

df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'),index=[0, 1])
df4 = pd.DataFrame([['C0','D0'],['C1','D1']], columns=list('BD'), index=[0, 1])
pd.concat([df3,df4],join='inner')    #column B is same in both, so only B comes.

Empty DataFrame
Columns: []
Index: [0, 1, 0, 1]


B
0  B0
1  B1
0  C0
1  C1

In [44]:
#Append
df3 = pd.DataFrame([['A0','B0'],['A1','B1']], columns=list('AB'),index=[0, 1])
df4 = pd.DataFrame([['C0','D0'],['C1','D1']], columns=list('AB'), index=[3, 4])
df3.append(df4)

A   B
0  A0  B0
1  A1  B1
3  C0  D0
4  C1  D1

In [52]:
#Merge and join

df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],'hire_date': [2004, 2008, 2012, 2014]})
df3=pd.merge(df1,df2)  #merges on common column name 'employee' and provide new dataframe
print(df3 )               # order of common column does not matter..

#many to one joins
df4=df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],'supervisor': ['Carly', 'Guido', 'Steve']})
print (pd.merge(df3,df4))

#many to many joins

df5=df5 = pd.DataFrame({'group': ['Accounting', 'Accounting','Engineering', 'Engineering', 'HR', 'HR'],
                        'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']})
df5
pd.merge(df1,df5)  #create cross product between mltiple values..now two 'bob one math and other spreadsheets'

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [56]:
#specifing key
print(pd.merge(df1,df2,on='employee'))  #if key name is same in both DataFrame.

df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})  #if key name is different
print(pd.merge(df1,df3,left_on='employee',right_on='name'))
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [2]:
#join
#df1=pd.set_index('employee')  #python 2 does not support set_index
#df2=pd.set_index('employee')
import numpy as np
import pandas as pd
df1 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'Engineering', 'HR']},index=['Bob', 'Jake', 'Lisa', 'Sue'])
df2 = pd.DataFrame({'hire_date': [2004, 2008, 2012, 2014]},index=['Lisa', 'Bob', 'Jake', 'Sue'])
df1.join(df2)  #join will work only on index values.

group  hire_date
Bob    Accounting       2008
Jake  Engineering       2012
Lisa  Engineering       2004
Sue            HR       2014

In [3]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue','Peter'],'group': ['Accounting', 'Engineering', 'Engineering', 'HR','HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue','Jane'],'hire_date': [2004, 2008, 2012, 2014,2010]})
print(pd.merge(df1,df2,how='inner'))
print(pd.merge(df1,df2,how='outer'))
print(pd.merge(df1,df2,how='left'))
pd.merge(df1,df2,how='right')

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
  employee        group  hire_date
0      Bob   Accounting     2008.0
1     Jake  Engineering     2012.0
2     Lisa  Engineering     2004.0
3      Sue           HR     2014.0
4    Peter           HR        NaN
5     Jane          NaN     2010.0
  employee        group  hire_date
0      Bob   Accounting     2008.0
1     Jake  Engineering     2012.0
2     Lisa  Engineering     2004.0
3      Sue           HR     2014.0
4    Peter           HR        NaN


employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
4     Jane          NaN       2010

In [4]:
#aggregation
#cont(), sum(), mean(), median(), mode(), std(),var(),mad()(mean absolute deviation),prod()(product of all items)
 #groupby key
df3=pd.merge(df1,df2,how='right')
df3.groupby('group').count() #note no computation is done untill no aggregation is called.


employee  hire_date
group                           
Accounting          1          1
Engineering         2          2
HR                  1          1

In [7]:
print(df3)
df3.groupby('group').aggregate([min,max])  #customized aggregation operations
df3.groupby('group').aggregate({'employee':'count','hire_date':'max'})  #diffrent operations on diffrent columns

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
4     Jane          NaN       2010


employee  hire_date
group                           
Accounting          1       2008
Engineering         2       2012
HR                  1       2014