In [8]:
#pandas practice
import pandas as pd 

#series from list or array..
sr=pd.Series([1,2,3,4,5,6,7,8])
print(sr[1:3])

sr=pd.Series([1,2,3,4,5,6,7,8],index=['h','b','c','d','e','f','g','a'])
print(sr)

pd.Series(5, index=[100, 200, 300])
print(sr)

1    2
2    3
dtype: int64
h    1
b    2
c    3
d    4
e    5
f    6
g    7
a    8
dtype: int64
h    1
b    2
c    3
d    4
e    5
f    6
g    7
a    8
dtype: int64


In [14]:
import pandas as pd 
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}

sr=pd.Series(population)
print(sr['California':'Illinois'])
print(sr.index)

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64
Index([u'California', u'Florida', u'Illinois', u'New York', u'Texas'], dtype='object')


In [20]:
import pandas as pd 

population=[38332521, 26448193,19651127,19552860,12882135]
#dataframe from list 
df=pd.DataFrame(population,columns=['Population'],index=['California', 'Florida', 'Illinois','New York','Texas'])
print(df)

#dataframe from dictionry.
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
df1=pd.DataFrame({'Population':population,'area':area})
df1

            Population
California    38332521
Florida       26448193
Illinois      19651127
New York      19552860
Texas         12882135


Population    area
California    38332521  423967
Florida       19552860  170312
Illinois      12882135  149995
New York      19651127  141297
Texas         26448193  695662

In [15]:
#dataframe form two dimentiona; Numpy Array..
import numpy as np
import pandas as pd

ar=np.random.randint(low=1,high=10,size=8).reshape(4,2)
NPdf=pd.DataFrame(ar,columns=['a','b'],index=np.arange(4))
NPdf

#Note  
print(NPdf.index[2])  #index value at 2 index
NPdf.index[2]=5     #try to change index ----Opppps Immutable index-can not be change--index are as Set in dataframe
                    #set can not be duplicate and change..

2


TypeError: Index does not support mutable operations

In [37]:
#data selection in series 
import numpy as np
import pandas as pd

ser=pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])
ser[(ser>3)&(ser<6)] #all other slicing operetaions are avaialbale..ser[1:3]..etc and loc[],iloc[] asl available.

#Data selection in DF
population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
df1=pd.DataFrame({'Population':population,'area':area})
df1['Density']=df1.area/df1.Population
df1.loc[((df1.area<600000)&(df1.area>150000)),['Population','Density']] #print only few with limited columns.

Population  Density
California    38332521  0.01106
Florida       19552860  0.00871

In [5]:
#UFuncs
import numpy as np
import pandas as pd

population={'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
popu=pd.Series(population)
area=pd.Series(area)
density=popu/area
density
popu+area  #to check all other refer previour numpy notebook.


California    38756488
Florida       19723172
Illinois      13032130
New York      19792424
Texas         27143855
dtype: int64

In [16]:
#very new to learn
import numpy as np
import pandas as pd
a=np.random.randint(0,10,(3,4))
print(a-a[1])

df = pd.DataFrame(a, columns=list('QRST'))
print(df-df.iloc[0])
print(df.subtract(df['R'],axis=0))
alter=df.iloc[0,::2]
b=df-alter
b

[[-4  6 -3  6]
 [ 0  0  0  0]
 [-4  1 -3  3]]
   Q  R  S  T
0  0  0  0  0
1  4 -6  3 -6
2  0 -5  0 -3
   Q  R  S  T
0 -4  0 -6  1
1  6  0  3  1
2  1  0 -1  3


Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN  3.0 NaN
2  0.0 NaN  0.0 NaN

In [20]:
np.mean(b,axis=1)

0    0.0
1    3.5
2    0.0
dtype: float64

In [21]:
#functions 
#isnull()
#notnull()
#fillna()
#dropna()
df = pd.DataFrame([[1,np.nan, 2],[2,3,5],[np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [41]:
print(df[df.isnull()])
print(df[df.notnull()])
print(df.dropna(axis='rows'))
print(df.dropna(axis='columns'))

#set count how many can be nan
print(df.dropna(axis='columns',how='all'))
print(df.dropna(axis='columns',thresh=2))

    0   1   2
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
1  2.0  3.0  5
   2
0  2
1  5
2  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6


0      1  2
0    1.0 -999.0  2
1    2.0    3.0  5
2 -999.0    4.0  6

In [44]:
#filling na values
df.fillna(-999)
df.fillna(method='ffill')
df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [48]:
import random as rng 
x = rng.rand(1E6)

AttributeError: 'module' object has no attribute 'rand'