In [36]:
import numpy as np

#how nympy saves time..
a=np.zeros((3,4))
print(a)

l1=np.array([1,2,3,4,5,6,7,8,9])
l2=np.arange(1,10,1)

l3=l1*2     #no needd to iterate the elemnets..
l4=l2*3
print(l2)
print(l4)
l5=np.linspace(1,12,6)  #gets 10 elemets in between 1to 20
l5

l1=np.array([1,2,3,4,5,6,7,8,9],dtype=np.int16)
print(l1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27]
[1 2 3 4 5 6 7 8 9]


In [14]:
print(l5.reshape(2,3))  #changes the shape of array but nop permanent 
l5   #still same one dimentional

[[ 1.   3.2  5.4]
 [ 7.6  9.8 12. ]]


array([[ 1. ,  3.2,  5.4],
       [ 7.6,  9.8, 12. ]])

In [17]:
print(l5.size)  #size tell total number of elements 
print(l5.shape)  #shape dimention of list.
print(l5.dtype)
print(l5.itemsize)  #as float64 takes 8 bytes per element.

6
(2, 3)
float64
8


In [51]:
#two dimentional array

l1=np.array([(1,2,3,4,5,6,7,8,9),(10,11,12,13,14,15,16,17,18),(19,20,21,22,23,24,25,26,27)])
print(l1)
print(l1.shape)
print(l1.dtype)
#l1=np.array([(1,2,3,4,5,6,7,8,9),(10,11,12,13,14,15,16)])   #no shape
#l1.shape

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
(3, 9)
int64


In [36]:
#boolean array
import numpy as np
bl=np.arange(12).reshape(3,4)
print(bl)
print(bl.dtype)
b=bl > 5
print(bl[b])  #Awwwwwsome
bl[b]= -10 #replaced evey element less than 5 with -10
print(bl)  


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int64
[ 6  7  8  9 10 11]
[[  0   1   2   3]
 [  4   5 -10 -10]
 [-10 -10 -10 -10]]


In [37]:
print(l5.min())
print(l5.max())

1.0
12.0


In [43]:
print(a.mean())
print(a.var())
print(a.std())

0.0

In [54]:
print(l1)
l1.sum(axis=1)  #AAAAAAAAAwesum
l8=np.array(["shan"])
l8

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


array(['shan'], dtype='<U4')

In [59]:
#load text

data=np.loadtxt('/home/shan/Downloads/shanwaz.csv',dtype='<U4',delimiter=',',skiprows=1)  
data

array([['shan', '24', '50'],
       ['noor', '24', '50']], dtype='<U4')

In [6]:
import numpy as np
a=np.array([(1,2),(3,4)])
b=np.array([[4,5],[6,7]])

print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a.dot(b))  # matrix product


[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]
[[0.25       0.4       ]
 [0.5        0.57142857]]
[[ 4 10]
 [18 28]]
[[16 19]
 [36 43]]


In [14]:
import numpy as np

a=np.array([[1,2,3],[7,8,9],[4,5,6]])
print(a)
print(a[1,2]) #access using indexing 
print(a[0:2,2])  #it will access the values from rows starting from 0 to 2(excuding 2) and pick 2nd column.
print(a[-1])      #last row
print([x for x in a.flat])

[[1 2 3]
 [7 8 9]
 [4 5 6]]
9
[3 9]
[4 5 6]
[1, 2, 3, 7, 8, 9, 4, 5, 6]


In [17]:
a=np.array([[1,2,3],[7,8,9],[4,5,6]])
b=np.array([[10,20,30],[70,80,90],[40,50,60]])

print(np.vstack((a,b)))  #very cool....
print(np.hstack((a,b)))   #very coooooolllllll


[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 20 30]
 [70 80 90]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 7  8  9 70 80 90]
 [ 4  5  6 40 50 60]]


In [23]:
a=np.array([[1,2,3,7,8,9,4,5,6],[10,20,30,40,50,60,70,80,90]])
print(a)
li=np.hsplit(a,3)
print(li[0])
print(li[1])
print(li[2])

[[ 1  2  3  7  8  9  4  5  6]
 [10 20 30 40 50 60 70 80 90]]
[[ 1  2  3]
 [10 20 30]]
[[ 7  8  9]
 [40 50 60]]
[[ 4  5  6]
 [70 80 90]]
